### ISSUE TITLE
[Errno 2] No such file or directory: 'src/autonomous_exploration/config/params.yaml'

### ISSUE THREAD

**Issue by Omar-Salem** [abdulkadrtr/ROS2-FrontierBaseExplorationForAutonomousRobot#1]

**Comment by abdulkadrtr** [comment]
Hello, 
make sure you execute the command `source install/setup.bash` while you are in your working directory to resolve the issue of finding the relevant file path. If the same error persists, you can modify line 12 in the file `autonomous_exploration/autonomous_exploration/control.py`.
