### ISSUE TITLE
Using package on another robot

### ISSUE THREAD

**Issue by yas28elg** [abdulkadrtr/ROS2-FrontierBaseExplorationForAutonomousRobot#3]
Hello ! 

Thanks for sharing your code. I'm trying to use it on a custom robot.

I followed the step you proposed for running the node (sim, robot and then ros2 run..) but the robot doesn't move. I made sure to change the topics names on the script to match the robot's. On rviz I can see my map and the output of my scanner.  

I did a bit of digging on the code and it seems that there is no path generated. It keeps sending the robot position as a goal. I think the issue comes from A* algorithm. I send different start and goal position but no goal is found and the closest path to the goal is the initial position. I also checked, there are free cells and frontier were successfully defined. 

Have you already encountered this kind of issue? Do you know where the problem could come from?

Thanks in advance !

**Comment by JoaoVictor0508** [comment]
Hey, could you solve it? I am facing the same problem and found your issue.

**Comment by yas28elg** [comment]
Hey! More or less, I decided to use Nav2 planner and controller.
