### ISSUE TITLE
Suggestion to previous issue #1 - FileNotFoundError: [Errno 2] No such file or directory: 'src/autonomous_exploration/config/params.yaml'

### ISSUE THREAD

**Issue by booth-algo** [abdulkadrtr/ROS2-FrontierBaseExplorationForAutonomousRobot#4]
I encountered a similar problem as described in [Issue #1](https://github.com/abdulkadrtr/ROS2-FrontierBaseExplorationForAutonomousRobot/issues/1). The `params.yaml` file is missing from the `src/autonomous_exploration/config` directory, which results in a `FileNotFoundError` when running the script.

The issue is that when cloning this repository into ros_ws/src, there is an extra layer (folder) which includes the `autonomous_exploration` package along with the README and licensing. 

Hence when it tries to look for the param file, it can't find it because the path is `src/ROS2-FrontierBaseExplorationForAutonomousRobot/autonomous_exploration` instead of `src/autonomous_exploration`. 

So other than a path change in the `control.py` file, you can also move the autonomous_exploration to under src (out of the folder) such that the it matches the expected hierarchy.

Hope this helps someone in the future.

**Comment by abdulkadrtr** [comment]
Thank you for your contribution. Good luck with your work.
