### ISSUE TITLE
The robot collided with an obstacle

### ISSUE THREAD

**Issue by csf329066629** [abdulkadrtr/ROS2-FrontierBaseExplorationForAutonomousRobot#6]
I wanted to experiment in an actual environment, so I only ran the SLAM node and the FE node (without running the simulation node). My robot was performing well initially, but it collided with the final obstacle(as shown in the picture). Is it an issue related to inappropriate parameter settings of the FE? Could you tell me the solution?
![fe](https://github.com/user-attachments/assets/6ec24871-016d-47bf-8481-f4ec0077cf1d)

**Comment by abdulkadrtr** [comment]
Hi,
You can try increasing the `expansion_size` value. If this does not work for your problem, try increasing the `robot_r` value.

The `expansion_size` value should be increased to prevent the robot from moving too close to defined obstacles on the map. The `robot_r` value represents the offset distance used by the collision avoidance system when the robot approaches dynamic or static obstacles that are not marked on the map.

https://github.com/abdulkadrtr/ROS2-FrontierBaseExplorationForAutonomousRobot/blob/0a1ec895ff0de1272968e7c2d7e741f3909c3596/autonomous_exploration/config/params.yaml#L3

https://github.com/abdulkadrtr/ROS2-FrontierBaseExplorationForAutonomousRobot/blob/0a1ec895ff0de1272968e7c2d7e741f3909c3596/autonomous_exploration/config/params.yaml#L5

**Comment by csf329066629** [comment]
I would like to ask if you could delete this issue. I sincerely apologize for any inconvenience this may cause and greatly appreciate your understanding and cooperation in resolving this matter.
Thank you for your prompt attention to this request.

**Comment by abdulkadrtr** [comment]
I’m glad to hear that your issue has been resolved. I have closed this issue but decided not to delete it for future reference. This way, others who encounter the same problem can look at this discussion to resolve their issues.
